# Generated by Django 3.1.7 on 2021-04-16 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0003_auto_20210401_2356'),
        ('msgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addfavoritecv',
            options={'ordering': ['cvs'], 'verbose_name': 'Избранные резюме', 'verbose_name_plural': 'Избранные резюме'},
        ),
        migrations.AlterModelOptions(
            name='addfavoritevacancy',
            options={'ordering': ['vacancy'], 'verbose_name': 'Избранные вакансии', 'verbose_name_plural': 'Избранные вакансии'},
        ),
        migrations.AlterField(
            model_name='addfavoritevacancy',
            name='employer',
            field=models.ManyToManyField(related_name='employers', to=settings.AUTH_USER_MODEL, verbose_name='Работодатели'),
        ),
        migrations.AlterField(
            model_name='addfavoritevacancy',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='employer.vacancy', verbose_name='Вакансии'),
        ),
    ]
