# Generated by Django 3.1.7 on 2021-04-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20210331_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='created_by',
            new_name='user',
        ),
    ]
