# Generated by Django 3.1.7 on 2021-04-20 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0007_auto_20210416_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_creator', to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.CreateModel(
            name='BookmarkCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_cv', to='employee.cv', verbose_name='Резюме')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_concern', to=settings.AUTH_USER_MODEL, verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Избранные резюме',
                'verbose_name_plural': 'Избранные резюме',
                'ordering': ['cv'],
            },
        ),
        migrations.AddField(
            model_name='cv',
            name='employer_bookmarked',
            field=models.ManyToManyField(related_name='bookmark_keeper', through='employee.BookmarkCV', to=settings.AUTH_USER_MODEL, verbose_name='владелец закладки'),
        ),
    ]
