# Generated by Django 3.1.7 on 2021-06-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20210614_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecv',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cv', to='employee.cv', verbose_name='Вакансия'),
        ),
    ]
