# Generated by Django 3.1.7 on 2021-04-20 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0003_auto_20210401_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.CreateModel(
            name='BookmarkVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_concern', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_vacancy', to='employer.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Избранные вакансии',
                'verbose_name_plural': 'Избранные вакансии',
                'ordering': ['vacancy'],
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employee_bookmarked',
            field=models.ManyToManyField(related_name='bookmark_holder', through='employer.BookmarkVacancy', to=settings.AUTH_USER_MODEL, verbose_name='владелец закладки'),
        ),
    ]
