# Generated by Django 3.1.7 on 2021-04-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210420_2019'),
        ('employer', '0004_auto_20210420_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cv', to='employee.cv', verbose_name='Резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_vacancy', to='employer.vacancy', verbose_name='Вакансия')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='response',
            field=models.ManyToManyField(related_name='vacancy_cv', through='employer.Response', to='employee.CV', verbose_name='резюме'),
        ),
    ]
