# Generated by Django 3.1.7 on 2021-06-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20210615_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='response',
            new_name='cv_response',
        ),
    ]
