# Generated by Django 3.1.7 on 2021-06-11 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20210420_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['vacancy', 'cv'], 'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
        migrations.AddField(
            model_name='response',
            name='message',
            field=models.TextField(blank=True, verbose_name='сообщение'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_fk', to='employer.company'),
        ),
    ]
